### ISSUE TITLE
minify html

### ISSUE THREAD

**Issue by dominikstrasser** [storyblok/quickstart#2]
So my PageSpeed is now 99 / 99 - the only thing missing is "minify html"
is this something your rendering service should provide or am i missing something in my gulpfile?

**Comment by DominikAngerer** [comment]
Its even easier than that - you can simply wrap the whole HTML in the page.liquid into {{spaceless}} {{/endspaceless}} and you're ready to go!

**Comment by DominikAngerer** [comment]
@dominikstrasser You can have a look how Alex did it here: https://github.com/onefriendaday/getspeed100/blob/master/views/page.liquid

**Comment by dominikstrasser** [comment]
works ;)
![image](https://user-images.githubusercontent.com/7978324/27997356-f045b9e4-64f6-11e7-962e-262587430e1a.png)
