### ISSUE TITLE
Install fails. Probably due outdated packages. 

### ISSUE THREAD

**Issue by kmukku** [storyblok/quickstart#4]
I tried "cd ./project && npm i && npm run dev" but seems not to work. Mostly errors after errors related to @babel/register.

**Comment by kmukku** [comment]
Gulp
CLI version: 2.3.0
Local version: 3.9.1
NPM
7.0.15
Node
v15.4.0

**Comment by DominikAngerer** [comment]
Hey there!

We've just launched a new version which can be used with the latest node version. It is built upon rollup for the builds itself:

https://github.com/storyblok/rendering-service
